# Generated by Django 4.2.4 on 2025-06-19 14:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0005_product_is_sale_product_sale_price'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='is_sale',
            new_name='sale',
        ),
    ]
