# Generated by Django 4.2.4 on 2025-06-19 16:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0007_alter_product_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.ImageField(default='uploads/product/iphone.webp', upload_to='uploads/product'),
        ),
    ]
