# Generated by Django 4.2.4 on 2025-06-19 16:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0008_alter_product_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.ImageField(default='andr.webp', upload_to='uploads'),
        ),
    ]
